CREATE TABLE TB_SORT_RESULT ( 
  NO NUMBER(5, 0) NOT NULL ENABLE
  , ALGORITHM VARCHAR2(50)
  , ARRAY_TYPE VARCHAR2(50)
  , ARRAY_SIZE NUMBER
  , TIME_SEC NUMBER(8, 3)
  , COMPARE_COUNT NUMBER
  , PRIMARY KEY (NO, ALGORITHM, ARRAY_TYPE, ARRAY_SIZE)
); 

